name: Deploy Portfolio Website


on:
push:
branches: ["main"]


jobs:
deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v4


- name: Setup Terraform
uses: hashicorp/setup-terraform@v2
with:
terraform_version: 1.6.0


- name: Configure AWS credentials
uses: aws-actions/configure-aws-credentials@v2
with:
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: us-east-1


- name: Terraform Init & Apply
working-directory: terraform
run: |
terraform init
terraform apply -auto-approve


- name: Get bucket name
id: tfoutput
working-directory: terraform
run: echo "bucket=$(terraform output -raw website_endpoint)" >> $GITHUB_OUTPUT


- name: Upload site to S3
run: |
aws s3 sync site/ s3://$(terraform output -raw bucket_name) --delete
